version: "3.9"
services:
  database:
    image: postgres
    container_name: dice_database
    volumes:
      - ./.database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: on-failure
  cache:
    image: redis/redis-stack
    container_name: dice_cache
    volumes:
      - ./.cache:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: on-failure
