from handlers.admin import AdminHandler
from handlers.balance import BalanceHandler
from handlers.callback import CallbackHandler
from handlers.lottery import LotteryHandler
from handlers.profile import ProfileHandler
from handlers.pvb import PVBHandler
from handlers.pvpc import PVPCHandler
from handlers.start import StartHandler
from handlers.support import SupportHandler
