"""Changed PVPC model

Revision ID: 58eee7efb708
Revises: a4a16d57900b
Create Date: 2023-12-01 02:30:00.894259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58eee7efb708'
down_revision: Union[str, None] = 'a4a16d57900b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games_pvpc', 'opponent_tg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games_pvpc', 'opponent_tg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
