"""Changed games_pvb

Revision ID: b6e58e31b3b8
Revises: 2d8577cd6c1c
Create Date: 2023-11-19 15:14:11.215738

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b6e58e31b3b8'
down_revision: Union[str, None] = '2d8577cd6c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'games_pvb',
        'player_won',
        existing_type=sa.BOOLEAN(),
        nullable=True
    )
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


# noinspection PyTypeChecker
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        'users',
        type_='unique'
    )
    op.alter_column(
        'games_pvb',
        'player_won',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    # ### end Alembic commands ###
