# noinspection SpellCheckingInspection
"""Changed transactions table

Revision ID: e2e719f621b0
Revises: 9bcfb3328359
Create Date: 2023-12-11 09:55:39.632197

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e2e719f621b0'
# noinspection SpellCheckingInspection
down_revision: Union[str, None] = '9bcfb3328359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'games_pvb',
        'player_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False
    )
    op.alter_column(
        'games_pvp',
        'creator_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False
    )
    op.alter_column(
        'games_pvp',
        'opponent_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvp',
        'winner_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvpc',
        'creator_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False
    )
    op.alter_column(
        'games_pvpc',
        'opponent_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvpc',
        'winner_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=True
    )
    op.add_column(
        'transactions',
        sa.Column(
            'recipient_details',
            sa.String(),
            nullable=True
        )
    )
    op.add_column(
        'transactions',
        sa.Column(
            'recipient_bank',
            sa.String(),
            nullable=True
        )
    )
    op.alter_column(
        'transactions',
        'user_tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False
    )
    op.drop_column(
        'transactions',
        'btc_to_rub_currency'
    )
    op.drop_column(
        'transactions',
        'withdrawal_btc_wallet'
    )
    op.drop_column(
        'transactions',
        'withdrawal_bank_name'
    )
    op.drop_column(
        'transactions',
        'withdrawal_card_details'
    )
    # noinspection SpellCheckingInspection,PyTypeChecker
    op.alter_column(
        'users',
        'tg_id',
        existing_type=sa.INTEGER(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_tg_id_seq'::regclass)")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # noinspection SpellCheckingInspection,PyTypeChecker
    op.alter_column(
        'users',
        'tg_id',
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_tg_id_seq'::regclass)")
    )
    op.add_column(
        'transactions',
        sa.Column(
            'withdrawal_card_details',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True
        )
    )
    op.add_column(
        'transactions',
        sa.Column(
            'withdrawal_bank_name',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True
        )
    )
    op.add_column(
        'transactions',
        sa.Column(
            'withdrawal_btc_wallet',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True
        )
    )
    op.add_column(
        'transactions',
        sa.Column(
            'btc_to_rub_currency',
            sa.NUMERIC(),
            autoincrement=False,
            nullable=False
        )
    )
    op.alter_column(
        'transactions',
        'user_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.drop_column(
        'transactions',
        'recipient_bank'
    )
    op.drop_column(
        'transactions',
        'recipient_details'
    )
    op.alter_column(
        'games_pvpc',
        'winner_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvpc',
        'opponent_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvpc',
        'creator_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'games_pvp',
        'winner_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvp',
        'opponent_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=True
    )
    op.alter_column(
        'games_pvp',
        'creator_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    op.alter_column(
        'games_pvb',
        'player_tg_id',
        existing_type=sa.BIGINT(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
