"""Added details model

Revision ID: 7defb5171f5a
Revises: 44093403f387
Create Date: 2023-12-19 10:19:12.172799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7defb5171f5a'
down_revision: Union[str, None] = '44093403f387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_tg_id', sa.BIGINT(), nullable=False),
        sa.Column('method', sa.String(), nullable=False),
        sa.Column('withdraw_details', sa.String(), nullable=False),
        sa.Column('withdraw_bank', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    # ### end Alembic commands ###
