from .admin import AdminHandler
from .balance import BalanceHandler
from .callback import CallbackHandler
from .lottery import LotteryHandler
from .private_dice import PrivateDiceHandler
from .private_text import PrivateTextHandler
from .profile import ProfileHandler
from .pvb import PVBHandler
from .pvp import PVPHandler
from .pvpc import PVPCHandler
from .start import StartHandler
from .support import SupportHandler
