from infrastructure.handlers.admin import AdminHandler
from infrastructure.handlers.balance import BalanceHandler
from infrastructure.handlers.callback import CallbackHandler
from infrastructure.handlers.lottery import LotteryHandler
from infrastructure.handlers.private_dice import PrivateDiceHandler
from infrastructure.handlers.private_text import PrivateTextHandler
from infrastructure.handlers.profile import ProfileHandler
from infrastructure.handlers.pvb import PVBHandler
from infrastructure.handlers.pvpc import PVPCHandler
from infrastructure.handlers.start import StartHandler
from infrastructure.handlers.support import SupportHandler
